### ISSUE TITLE
No longer searches and switching to Google search

### ISSUE THREAD

**Issue by lmkunert** [kejadlen/giphy.alfredworkflow#17]
Getting strange behavior as of late in Mojave. I type the giphy keyword and then star typing a keyword to search on and it shows "Searching giphy..." for a second and then suddenly shows a Google search instead for that full string I'm typing in like this:
![image](https://user-images.githubusercontent.com/3722319/57105453-68efaf00-6cf0-11e9-93b0-d18ffd2193a9.png)

**Comment by rylnd** [comment]
FWIW, I'm receiving same as of a few days ago; I can't speak to what's changed, other than perhaps an alfred update? I'm on alfred v3.8.1. Debugging shows the following:

<img width="832" alt="Alfred_Preferences" src="https://user-images.githubusercontent.com/657252/57106138-49598600-6cf2-11e9-8f40-235eddf3287a.png">

(the error only happens once for each failure).

**Comment by kejadlen** [comment]
Had to update the API key, though I'm not sure why. Might be related to it being a development key rather than a production key, but it's kind of a hassle. If there are further issues with the API key, I might have to do so, but let's see if this continues to work.

Fixed in [v3.2.1](https://github.com/kejadlen/giphy.alfredworkflow/releases/tag/v3.2.1).

**Comment by rylnd** [comment]
👍 thanks @kejadlen, that fixed it for me in v3.2.1. I haven't seen how you're using the API key, but if this is a rate-limiting issue or something similar I'm happy to help with allowing a user-provided key.
